---
- name: Cloning oslo.cache source repository for development
  become: true
  git:
    repo: "{{ oslo_cache_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{  oslo_cache_dev_repos_pull }}"
    version: "{{ oslo_cache_source_version }}"
    